language: php

php:
  - 5.4

branches:
  only:
    - master

install:
  - composer install --prefer-dist
  - echo "yes" | sudo add-apt-repository ppa:avsm/ppa-testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam
  - export OPAMYES=1
  - opam init
  - opam install travis-senv
  - eval `opam config env`
  - travis-senv decrypt > ~/.ssh/id_rsa
  - chmod go-rwx ~/.ssh ~/.ssh/id_rsa

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: ant configure build -Dprofile=jeroboam -Dphp.executable=php

after_success: ant deploy -Dprofile=jeroboam -Dphp.executable=php

env:
  global:
  - secure: KRdWE91ScvvYj4QPCSSkZv7ECrQ7O5MiqXshYk229rLhknFcOJ7chcLtWFG825ySC8WxBO7M0Z9K6CQSC4z0b/7MmdGG8crE8X37uNueBUSeOHputjOOPb6U7ovUpJx/diPj9485DBAaHZMSbfhLkYcYglhh/8gPXhQ1o3Eco+U=
  - secure: ZcklOv5jcZN3xd9nZtCnVwQnWDCOoexdIPPFWGB6vgk4ThZ+CJE4GWIAk53m6HLhY9617SWSLqppJPVcZfsciHpCJD8W6NnW4MqSwVTYEqxnoh8wfL+pgT1FUUKqpxIFws1e/OJjG60kiV9OmFf1L+GiJFDQRNuX3MwRd4N3ah0=
  - secure: JI5BmtHMtRhQH+F9t6aUREdC4Yqo41depqYNOx/jx+sqqvPVr3XLLMzGE4tBxJZdbYtWs9vlQs4/t1QQYPbKikx9CNiiKT2IzELh4AVI6XltRHfH+0X7Y+LbDIAn+yYCZlu6bTrf4/lZenQ55DlKzk/70pwxpxY6ufq4LXQ0N1E=
  - secure: JEUEQDxkfHABxzSwfOVZ13k+N9J1KxsUauRFENcrPn5g+C/yZtKmjfFB4KV5lJ4EVAkxWGeIHpcNa/R5f+Lss016SshzT2TfORR88vtxTO/blsW4zYoR0WXxpZev3oVsUKQYyYwKL/uh1GAgz3UB49ZgQD9MJ7abO3f6nSxIMjo=
  - secure: bD7xV244U+6Fea4NWwolgRH2R39aNJCAbdmOY/PIYPHGosffIj/1GBfhuw3IXh/2XWz8nXip+uhs7deUw4mKwJs+V1Ev99LW7qjUuLxhaZPdURKNEjkynMKIzDL/Zqnn/IJF2FS/uQJcBhHlgBg/rA/4ewxrguMOThUUcVhbjeg=
  - secure: P3m1aP2XmHxroJf4n7w7+5oHkpFkhTcvhRUAkY3E6nGCdSffiifgBOvkVYRNoRtMa4qaROGSRVc0oKaWS//aqQvHVBZUpUSNj76lEM+6P6xYCHKKMC5QUmK7GmWb9BHvkpxyCdmK+J6mYKYnMZNnnNmmJAm6WXBfT9eoNzJ27jc=
  - secure: Ht3GMDCnKjHSs1ZWEX88YrGHAFUxHy+D5FnT6nH7eva8kJMXQACl9Vi/X3o3p/cq6fV4qs+nhOBDTQ3wbTzHysk8wSxdWN8CnT6RIyYyS/jVG8mQ3QTewE62xRnauByjAyaDAVaZNK+K/PO23Ra1zSGjJ1+7LtR21ro78/BcfAQ=
  - secure: JH1PwppdhPg0dE7xthB1XIeGtrZms8UEgVx+I5A5iaS6aMoqbyoMpFa6tHBW+Lg5U2KAuCE0I5wO967Ikv65TLeDBoK5lHqJjr8Ln+h/75MjFUuaABlieFwo7xrVcnthQu9QkkwNV5mz2Z6QOLol87QUfYaOLWJ3ZvXwXggN15c=
  - secure: c9fSnw5X8HiLuhdIUfoyRZjQ8wDhFpddBUvt5pxmPlrycUrufmhjR6Bx2A5f1Y+MrIxHWolxMmqHft3vbZ7u1K2o96+D8dciIOneJoQfJz6rUtBc6L5f8ZVnMGa0RMDW5npWDLGKuJA9wsModrEcagOA+/Dh0WNUYpfQ90DuQfk=
  - secure: WjY2QflcgezQQ+5ieDWhY8gOx2Az5ueUMCrd/oxiR0V4kOPFHAkf6Wp28cjibkQt23nHQDbXK1FbOIsu7yIOLoRW4rMgeirZ9suwIYg8Xh8klgroGRDA86K8XcNHH6XLhEAysC3yLKHdscnvn/sRVt5BwPRryrK+JWjoynWO0BQ=
  - secure: X3n5fc2eFv5PVkoTv28yGK6rqjpO9amoCHOVEpxw5vQEK3jLZWpSNSMY/q7gVxUFm+yJAau22Y9FDaL5akhea/xmKoT/Fy7k/3Pq65aKcVev/RtrvvnE+KDBWcjQqMuPgh9AdsO6OhG1vuIc+UKIqaJOEWcF7NANbY6+xRH+6ls=
  - secure: Wbc+oDU1DJKs4wpmXnJQPkQ1QROg2wbAIJOybg2y6wymAD9vxjEDekUbCxWAHH00Cru8BclJfylvhnStl4Jiiu8KR5x78ouibvDniMmVS1HPYHbo6MplCdy9NRrL2mkvKGoYRzUw/zNRI/Nle9pkQVdenSDbAXGkDRlIlLiaU8g=
  - secure: MKKW78GHMOAZIzuDHo8wQgiahjYJooYtnjR5HAIHLg6FuzCIF95Gsyibz75PWAuzsCYeAax3oVJwq1aUFk0s8Biby/QNwpZUSRXW1lbce8Pd/6MqfgI0jHnbrYZYQASxtcAsDm+xEhSdXBkOL61IvMrAMkKQ4ba1dUedR3ChlhE=
  - secure: HsevhfukvUpb/X9iMROj4DK/JUeoiWCB24OgBBx1cWXc+JkP+VTF56KcoIqW5XwhMwvfDC8GkLZnajT2A4bUYR1hAcHk1vlc+SSL62uPg6/jMROgguBCSAwQq3MuF3W7I2QTbGrUQ1pN7FqwWbdnizsIkYR+lI2Lj7Mrkob3fkU=
  - secure: iAFyLslRhF2pBui5Tb6CdzrBv/F8KWrn65xcvp9oVTpr9zWhyPmjCZfHhmFEA3TdXU2BWLATz1I6w+kshd6pnBnWVd3JuUCI7+4Qb4OPQZ55uZDd2MLUcQfY6GyZ7bgIqRUycbn1M38iOq3XYwPQZ7E7W7XpTDT12MUu+wXcQ5g=
  - secure: T9RMkmCwH3PNb4pKbTnnQZw063mqi1mKF9YYg3xfkx8NglNFYs9NunmBdz4TXSdJwQ1QA46mUBV3lVifiXYA+dBi5oKzDm0UN0wKBXpuWzqr33u7eFvKov7Ze4ejXRdaIlBVG1b3MnfQDph8ukci6JxBdD5J+WIU5OtlUtjF8Do=
  - secure: R7XANwbQaKURwOd7KJLX11j1WfkXReRL9JtnmeYjyYP/TuytrPi8qFpb5GQMud+eWFBUwmNgkG3T8j1hVk3AAAtwCszKsIvhRPnQLR2SVjN6KY8ZR3fBhQJY/VZl4YbawXzdWsB3x6yyOKsImuyCu8V8aCufOO9Y0snZLBkuIPM=
  - secure: PL+uJhMY0v7bwcvbjxDWud6uHNsz/+kaqrgupouoO+kzvfpVFw8HuQEQJ80V9NTnlZj7n8Zp9rC99TXP87j2uclQqwqWvhh1m8rv4Q9FlTP1RGXVspwKhuibnAaIH6djvxIQNpyvB5m/hT++qyvws0vPzQJu3TBf1RgZVBc4kgk=
  - secure: ZL7Hc6uYsPWGcOnum20/yCNsboidiXL2nqd9yzhRgAVcxoXh8bmK2D1kTlbgOhyCrOURWby5Q4krJ+xh9dRcWmy8tB+GyEYps3K8VH1i78T6e9gYSs4cim25TUhT8a0ky5gEOX5+LYUx0qvAfvkz2l6KZtxn4I/fx0zHnCOvSeo=
  - secure: I9jNgiotLgXfmckMsypMbu3ILR/NO0121+7/JrJi1++A702rx29oxFizildw5l6p2RBmscUeJdRtZZDjIhLJ7grjH5zM07czOxB1b7icrDP4LrU5wtpZ3l9sbiK4kIzbfXh9V056rZsEX+YyIxW9ez2OeVaUCSc0hH/r2Hv5QoI=
  - secure: M8/k8NEGADicKWmn5eEZ5dNVtoIeGaRPPJ9yyVG0sPMmZCbNH1dJstTkYEWRXBaGP6gXS8+heqlSzSQhAKgpHQToDGw6raO9kCc7Wdxus8vVOsM5o5qWfMBZGPv/6+vWFdm8GkWFYpjZnMogqNK2v0m6LehKal0TfSFV2vDqcvI=
  - secure: PTioSsdXuftHoGMDZ/QnU6HNNMKs5aAFNa3B3dOjaaLBYewoIO/e3dKGAddjsWcYEj+PflfbBxO2mtQ4klvuCW2qn4zUkS/RExL1YFPeClL9GCZiJ6hEnLE4L45fqEORzRFbqkMMYslkQLN/lLfxXpmrQ0Jv3/HgsET2fe2GzRs=
  - secure: DpmonJBqX6/AuN7qiGS/kK92E/yckXIkdslsc9jzM0KW4UtE17HgArfWBnJdFgZRZJm8u5P8BinZeLsie5z3HfH+L0vgftWczU4JUliNI7ksLCa8y1f2jaYNbVJjL63VcVTbTrHmShStX5KSG+FuYukUH2yj0OocdB8rqjnYnbY=
  - secure: aRxyNAUtN2kDIROSJsUvK0h3SkCcUB+7702IQQDOVlcRxZBz3XTb5vLDvL/vyVEIP33RrBf3DtXyac+kqFHmgxj5k6X5rQZjWI16jNB/v3VK9mgQLvjyL9PSzwM0XL3w0CkT3530LJ79G4l+S4ej+wfpXX8hUXnsB0gJICczlA8=
  - secure: YLRfyklZHE/RdI4AdkhTQ7IcNcqEKKbI/0TdfrVyrLXB+Uqvfm6SvhwTIriHnMOBYALYvvekSwePG5KYwOXk9d05UxyfvYamhhQPiPmz7X9yNboXlW9lQ7niPV+kadZQaGrl7QcSrCOHFXqbbMHiHc11KbJgM9Ljj15JDnxP+5o=
  - secure: jJzsJ7K8CdnpCt2V0glknwfC+D2ZR8iNezvgTmwwbWFeJpSVRDMCcUXOb7jSEH16d5KQHsFOftuLD0x992y0CFwbfwgEwMBs1lqyi7LTPWWa+r04MdhyWCOw4msWsX5Yio9Q7w/sPaHGAZ64bpQq/BbQKWUNyz3e8iT2upLVxHM=
  - secure: aTxj0HVs+P+/58N4Wka12niw1WrVLO+pc927RgRVpM50I5Nx9UPT8A0N0K+P2QnroTkz5uHplon5TxW1JCrDcRCSyl3pFgmkhLOjVgWM5rjn+gLToy8PtA21elvI73wbq4zDem5jf0f0BdyL7l1/lcCRB0pb37QKJ9lyZyZx1fI=
  - secure: gHoO5gRxY51+K3EYrBdxUu7/5zDMcGMTXwCta8H6Hq8WZaZUaG0XKlZMiqGwedVrHsCs6EPUSMHpWSgqIZI/be+d9QMppjpWVrNn1myzxuJBbyLBqUB/Pw8gD84+9hZ8kFdh1nrbz5ZDCLzF7cc/uTwnDNPVRJfAnIxVN3OBRRI=
  - secure: cQ3Pcj6d0v3IXXjIrvla2/Uk8KlsTYATGsscTspgRuwCpLC47VjioLX7NU3Z2y8m4mnqMa5wvu3l6koBxca4Us2ooGHP26YCP3vgbPh+aiNGsa0cjIkYaTc7dK9TZ0+9KG0lMoh0P4UYsgfNokwJRxsG/pJ9RueDyNqWT/msr8c=
